-- 01
SELECT 
	MAX(SALARY) AS "MAXIMUM",
	MIN(SALARY) AS "MINIMUM", 
	SUM(SALARY) AS "SUM",
	ROUND(AVG(SALARY)) AS "AVERAGE"
FROM
	EMPLOYEES;
-- 02
SELECT 
	JOB_ID,
	MAX(SALARY) AS "MAXIMUM",
	MIN(SALARY) AS "MINIMUM", 
	SUM(SALARY) AS "SUM",
	ROUND(AVG(SALARY)) AS "AVERAGE"
FROM
	EMPLOYEES
GROUP BY
	JOB_ID;
-- 03
SELECT
	JOB_ID,
	COUNT(JOB_ID) AS "COUNT(*)"
FROM 
	EMPLOYEES
GROUP BY
	JOB_ID;
-- 04
SELECT
	COUNT(DISTINCT MANAGER_ID) AS "NUMBER OF MANAGERS"
FROM 
	EMPLOYEES
WHERE
	MANAGER_ID IS NOT NULL;
-- 05
SELECT
    MAX(SALARY) - MIN(SALARY) AS "DIFFERENCE"
FROM
    EMPLOYEES;
-- 06
SELECT
    MANAGER_ID,
    MIN(SALARY)
FROM
    EMPLOYEES
WHERE
    MANAGER_ID IS NOT NULL
GROUP BY
    MANAGER_ID
HAVING
    MIN(SALARY) >= 6000;
-- 07
SELECT
    D.DEPARTMENT_NAME AS "NAME",
    D.LOCATION_ID AS "LOCATION",
    COUNT(*) AS "NUMBER OF PEOPLE"
FROM
    DEPARTMENTS D, EMPLOYEES E
WHERE
    D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY
    D.LOCATION_ID, D.DEPARTMENT_NAME;
-- 08
SELECT 
    COUNT(*) AS "TOTAL",
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2005 THEN 1 END) AS "2005",
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2006 THEN 1 END) AS "2006",
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2007 THEN 1 END) AS "2007",
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2008 THEN 1 END) AS "2008"
FROM
    EMPLOYEES
WHERE
    EXTRACT(YEAR FROM HIRE_DATE) BETWEEN 2005 AND 2008;
-- 09
SELECT 
    E.JOB_ID AS "JOB",
    SUM(CASE WHEN D.DEPARTMENT_ID = 20 THEN E.SALARY END) AS "DEPT 20",
    SUM(CASE WHEN D.DEPARTMENT_ID = 50 THEN E.SALARY END) AS "DEPT 50",
    SUM(CASE WHEN D.DEPARTMENT_ID = 80 THEN E.SALARY END) AS "DEPT 80",
    SUM(CASE WHEN D.DEPARTMENT_ID = 90 THEN E.SALARY END) AS "DEPT 90",
    SUM(CASE WHEN D.DEPARTMENT_ID IN (20,50,80,90) THEN E.SALARY END) AS "TOTAL"
FROM
    DEPARTMENTS D, EMPLOYEES E
WHERE
    D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY
    E.JOB_ID;