--- TABLE 정의
CREATE TABLE IDENTITIES
(
    IDENTITY_ID INT NOT NULL,
    IDENTITY_NAME CHAR(20) NOT NULL,
    CONSTRAINT IDENTITES_PK
        PRIMARY KEY (IDENTITY_ID),
    CONSTRAINT CK_POSITIVE_IDENTITY_ID
        CHECK (IDENTITY_ID >= 0)
);

CREATE TABLE CAMPUS
(
    CAMPUS_ID INT NOT NULL,
    CAMPUS_NAME CHAR(20) NOT NULL,
    CONSTRAINT CAMPUS_PK
        PRIMARY KEY (CAMPUS_ID),
    CONSTRAINT CK_POSITIVE_CAMPUS_ID
        CHECK (CAMPUS_ID >= 0)
);

CREATE TABLE USERS
(
    USER_ID INT NOT NULL,
    USER_REG_DATE DATE DEFAULT NULL,
    USER_DEL_DATE DATE DEFAULT NULL,
    USER_LOGIN_DATE DATE DEFAULT NULL,
    USER_IDENTITY INT NOT NULL,
    USER_CAMPUS_ID INT NOT NULL,
    USER_NAME CHAR(30) NOT NULL UNIQUE,
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
    CONSTRAINT CK_POSITIVE_USER_ID CHECK (USER_ID >= 0),
    CONSTRAINT FK_COLUMN_1
        FOREIGN KEY (USER_IDENTITY)
        REFERENCES IDENTITIES(IDENTITY_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_COLUMN_2
        FOREIGN KEY (USER_CAMPUS_ID)
        REFERENCES CAMPUS(CAMPUS_ID)
        ON DELETE CASCADE
);

CREATE TABLE PROJECTS
(
    PROJECT_ID INT NOT NULL,
    PROJECT_NAME CHAR(30) NOT NULL,
    CONSTRAINT PROJECTS_PK
        PRIMARY KEY (PROJECT_ID),
    CONSTRAINT CK_POSITIVE_PROJECT_ID
        CHECK (PROJECT_ID >= 0)
);

CREATE TABLE DAILY_PEER_REVIEW
(
    DP_DATE DATE NOT NULL,
    USER_ID INT NOT NULL,
    PR_NUMBERS_PER_DAY INT NOT NULL,
    CONSTRAINT PK_DAILY
        PRIMARY KEY (DP_DATE, USER_ID),
    CONSTRAINT FK_DAILY
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,
    CONSTRAINT CK_POSITIVE_DAY
        CHECK (PR_NUMBERS_PER_DAY >= 0)
);

CREATE TABLE PEER_REVIEWS
(
    PR_ID   INT NOT NULL,
    PR_RATE INT NOT NUL
    PR_DATE DATE NOT NULL,
    PR_COMMENT CHAR(500) NOT NULL,
    PR_REVIEWER_ID  INT NOT NULL,
    PR_PROJECT_ID INT NOT NULL,
    PR_REVIEWEE_ID INT NOT NULL,
    CONSTRAINT PK_PEER_REVIEW
        PRIMARY KEY (PR_ID),
    CONSTRAINT FK_PROJECT_ID
        FOREIGN KEY (PR_PROJECT_ID)
        REFERENCES PROJECTS(PROJECT_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_REVIEWER
        FOREIGN KEY (PR_REVIEWER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE, -- 간편하게 DROP 하려고 설정함 추후에 삭제
    CONSTRAINT FK_REVIEWEE
        FOREIGN KEY (PR_REVIEWEE_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,
    CONSTRAINT CK_VALID_RANGE
        CHECK ((PR_RATE >= 0) AND (PR_RATE <= 5))
);
