--- CREATE VIEWS

-- USER_REVIEWS
CREATE VIEW USER_REVIEWS
AS
	SELECT
		U.USER_ID AS "USER_ID",
		PR.PR_ID AS "PR_ID",
		PR.PR_RATE AS "PR_RATE",
		PR.PR_DATE AS "PR_DATE",
		PR.PR_COMMENT AS "COMMENT",
		PR.PR_REVIEWER_ID AS "REVIEWER_ID",
		PR.PR_PROJECT_ID AS "PROJECT_ID",
		PR.PR_REVIEWEE_ID AS "REVIEWEE_ID"
	FROM
		USERS U, PEER_REVIEWS PR
	WHERE
		U.USER_ID = PR.PR_REVIEWER_ID
	WITH
	 	READ ONLY
;

-- USER REVIEW COUNT BY PROJECTS
CREATE VIEW USER_REVIEW_COUNT_BY_PROJECTS
AS
	SELECT
		USER_ID AS "USER_ID",
		PR_PROJECT_ID AS "PROJECT_ID",
		COUNT(PR_PROJECT_ID) AS "EVALUATE COUNT"
	FROM
		USER_REVIEWS
	GROUP BY
		USER_ID, PROJECT_ID
;
-- -- USER REVIEW COUNT WEEKLY
-- CREATE VIEW USER_REVIEW_COUNT_WEEKLY
-- AS
-- 	SELECT
-- 		DP.USER_ID AS "USER ID",
-- 		SUM(DP.PR_NUMBERS_PER_DAY) AS "WEEEKLY SUM"
-- 	FROM
-- 		DAILY_PEER_REVIEW DP
-- 	GROUP BY
-- 		USER_ID
-- 	HAVING
-- 		DP.DP_DATE IN (DATE )
-- ;

-- -- USER REVIEW COUNT MONTHLY
-- CREATE VIEW USER_REVIEW_COUNT_MONTHLY
-- AS
-- 	SELECT
-- 		DP.USER_ID AS "USER ID",
-- 		SUM(DP.PR_NUMBERS_PER_DAY) AS "WEEEKLY SUM"
-- 	FROM
-- 		DAILY_PEER_REVIEW DP
-- 	GROUP BY
-- 		USER_ID
-- 	HAVING
-- 		-- DP.PR_DATE IN THIS MONTHLY
-- ;

